In [1]:
import numpy as np
import mlp
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
Xraw = iris.data[:,:4]
Yraw = iris.target

### Pre-processing the raw data

#### Normalizing Features

In [3]:
X = (Xraw - Xraw.mean(axis=0))/Xraw.max(axis=0)

#### Encoding the Targets

In [4]:
Y = np.zeros((Yraw.shape[0],3))
Y[:,0] = np.where(Yraw == 0, 1, 0)
Y[:,1] = np.where(Yraw == 1, 1, 0)
Y[:,2] = np.where(Yraw == 2, 1, 0)

### Split data into Training, Testing, and Validation Sets

In [5]:
np.random.seed(1)

In [6]:
# split data into train, test, validation sets
ixs = np.arange(len(X))
np.random.shuffle(ixs)
X = X[ixs,:]
Y = Y[ixs,:]

In [7]:
Xtrain, Xtest, Xval = X[::2], X[1::4], X[3::4]

In [8]:
Ytrain, Ytest, Yval = Y[::2], Y[1::4], Y[3::4]

In [9]:
mlp1 = mlp.mlp(Xtrain, Ytrain, np.array([5]))

In [10]:
mlp1.arch

array([4, 5, 3])

In [11]:
mlp1.train(Xtrain, Ytrain, Xval, Yval)

Stopped after 17 epochs


In [12]:
mlp1.weights

[array([[  7.02234844e-01,  -2.14514083e+00,  -1.35849254e+00,
           1.52521419e+00,  -2.76542928e+00],
        [ -1.26193034e-01,  -1.84743205e+00,  -3.87687652e-01,
           3.33906378e-01,  -4.77249539e-01],
        [  2.49553542e-03,   2.56618250e+00,   1.71350413e+00,
           1.79154186e+00,  -2.57369824e+00],
        [ -8.77007855e-01,  -5.65301350e+00,  -3.60447512e+00,
          -3.11439119e+00,   5.74884236e+00],
        [ -1.26312603e+00,  -5.09211177e+00,  -3.17574015e+00,
          -4.43642304e+00,   7.95662642e+00]]),
 array([[-3.51137687,  1.81132696,  0.42201971],
        [-0.88364363,  1.1497938 , -1.37610687],
        [ 4.41753029, -6.80977866, -2.5214    ],
        [ 2.68486245, -2.58314549, -3.27461225],
        [ 1.40679533,  2.4895717 , -5.05873974],
        [-5.35150919, -7.14516933,  6.5562209 ]])]

In [13]:
mlp1.cfnmatrix(Xtest,Ytest)

Error: 0.052631578947368474


array([[ 10.,   0.,   0.],
       [  0.,  16.,   0.],
       [  0.,   2.,  10.]])